In [ ]:
import tensor as tf

ModuleNotFoundError: No module named 'tensor'

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

NameError: name 'tf' is not defined

In [ ]:
!pip install tensorflow # Install TensorFlow if not already installed

import tensorflow as tf  # Import

In [ ]:
tensor_one_d = tf.constant([2, 0, -3, 8, 9])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8  9], shape=(5,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
what is 1d and 2d tensor


SyntaxError: invalid decimal literal (<ipython-input-6-c417f335591e>, line 1)

In [ ]:
# prompt: tensor_three_d

tensor_three_d = tf.constant([
    [[1, 2, 0],
     [3, 5, -1]],
    [[1, 5, 6],
     [2, 3, 8]],
    [[1, 0, 2],
     [8, 9, 1]]
])
tensor_three_d

# Explanation of 1D and 2D tensors:

# 1D Tensor (Vector):
# A 1D tensor is a sequence of values, like a list or an array. It has only one axis (or dimension).  Think of it as a single row of data.  `tensor_one_d` above is an example. It's like a single row in a spreadsheet or a single list of numbers.

# 2D Tensor (Matrix):
# A 2D tensor is a collection of 1D tensors, arranged in a grid.  It has two axes - rows and columns.  Think of it as a table of data (like a spreadsheet) or a matrix in mathematics. `tensor_two_d` above is an example.  It's like multiple rows of data in a spreadsheet, where each row has the same number of columns.

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[ 1,  5,  6],
        [ 2,  3,  8]],

       [[ 1,  0,  2],
        [ 8,  9,  1]]], dtype=int32)>

In [ ]:
import tensorflow as tf

# Create three 3D tensors
tensor_fourd_1 = tf.constant([
    [[1, 2, 0],
     [3, 5, -1]],
    [[1, 5, 6],
     [2, 3, 8]],
    [[1, 0, 2],
     [8, 9, 1]]
])

tensor_3d_2 = tf.constant([
    [[4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15]],
    [[16, 17, 18],
     [19, 20, 21]]
])

tensor_3d_3 = tf.constant([
    [[0, -1, -2],
     [-3, -4, -5]],
    [[-6, -7, -8],
     [-9, -10, -11]],
    [[-12, -13, -14],
     [-15, -16, -17]]
])

# Combine the 3D tensors into a 4D tensor
tensor_four_d = tf.stack([tensor_fourd_1, tensor_3d_2, tensor_3d_3])

# Print the 4D tensor
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[  1   5   6]
   [  2   3   8]]

  [[  1   0   2]
   [  8   9   1]]]


 [[[  4   5   6]
   [  7   8   9]]

  [[ 10  11  12]
   [ 13  14  15]]

  [[ 16  17  18]
   [ 19  20  21]]]


 [[[  0  -1  -2]
   [ -3  -4  -5]]

  [[ -6  -7  -8]
   [ -9 -10 -11]]

  [[-12 -13 -14]
   [-15 -16 -17]]]], shape=(3, 3, 2, 3), dtype=int32)


In [ ]:
tensor_zero_d = tf.constant(3)
print(tensor_zero_d)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
1 tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

SyntaxError: invalid syntax (<ipython-input-13-fdaf2cbd15a5>, line 1)

In [ ]:
converted_tensor = tf.cast(tensor_bool, tf.int32)
print(converted_tensor)

NameError: name 'tensor_bool' is not defined

In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 5, 3), dtype=float32)


In [ ]:
X_abs = <<

SyntaxError: invalid syntax (<ipython-input-1-afcc216ac226>, line 1)

In [ ]:
x_1@x_2

NameError: name 'x_1' is not defined

In [ ]:
import tensorflow as tf

# Define the shapes
shape1 = (2, 3, 4)  # Shape of x_1
shape2 = (3, 4)     # Shape of x_2
shape3 = (4,)       # Shape of x_3

# Create the tensors
x_1 = tf.random.normal(shape1)
x_2 = tf.random.normal(shape2)
x_3 = tf.random.normal(shape3)

# Perform the multiplication
result = x_1 * x_2 * x_3

# Print the shape of the result
print(result.shape)

(2, 3, 4)


In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mayankpatel14/second-hand-used-cars-data-set-linear-regression")

print("Path to dataset files:", path)

100%|██████████| 24.3k/24.3k [00:00<00:00, 8.67MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/mayankpatel14/second-hand-used-cars-data-set-linear-regression/versions/1


In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

# Load the dataset into a pandas DataFrame
df = pd.read_csv('/Users/premkumar/Downloads/train.csv')

# Display the first few rows of the DataFrame (optional)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/premkumar/Downloads/train.csv'

In [ ]:
df = pd.read_csv('/Users/premkumar/Downloads/train.csv')  # No spaces

FileNotFoundError: [Errno 2] No such file or directory: '/Users/premkumar/Downloads/train.csv'

In [ ]:

    df = pd.read_csv("/Users/premkumar/Downloads/My Data/train.csv")  # In quotes

FileNotFoundError: [Errno 2] No such file or directory: '/Users/premkumar/Downloads/My Data/train.csv'

In [ ]:
df = df.read_csv("/Users/premkumar/Downloads/My Data/train.csv")  # No spaces

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

# Load the dataset into a pandas DataFrame
df = pd.read_csv('/Users/premkumar/Downloads/train.csv')

# Display the first few rows of the DataFrame (optional)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/premkumar/Downloads/train.csv'

In [ ]:
import pandas as pd

# Try different ways to specify the path:
# df = pd.read_csv('/Users/premkumar/Downloads/train.csv')  # No spaces
# df = pd.read_csv("/Users/premkumar/Downloads/My Data/train.csv")  # In quotes
# df = pd.read_csv('/Users/premkumar/Downloads/My\ Data/train.csv') # Escaped space

# Alternatively, use the copied path from the Finder's "Get Info" window:
file_path = ""  # Replace with your copied path
df = pd.read_csv("/Users/premkumar/Downloads/train.csv")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/premkumar/Downloads/train.csv'

In [ ]:
!pip install numpy pandas scikit-learn matplotlib seaborn tensorflow

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn for various ML algorithms
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# TensorFlow and Keras for deep learning
import tensorflow as tf
from tensorflow import keras

# Other useful libraries
import os
import time
import random

In [ ]:
import pandas as pd

# Load the dataset into a pandas DataFrame

df = pd.read_csv('/Users/premkumar/Downloads/trainme.csv ')  # Use the variable to read the file

# Display the first few rows of the DataFrame
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/premkumar/Downloads/trainme.csv '

In [ ]:
pip install pandas

In [ ]:
python read_csv.py

SyntaxError: invalid syntax (<ipython-input-5-c1da0707261b>, line 1)

In [ ]:
import os

file_path = '/Users/premkumar/Downloads/trainme.csv'  # Updated file path
exists = os.path.exists(file_path)

if exists:
    print("File found at:", file_path)
else:
    print("File not found. Check the path:", file_path)

File not found. Check the path: /Users/premkumar/Downloads/trainme.csv


In [ ]:
import pandas as pd

# Load the dataset into a pandas DataFrame
file_path = '/Users/premkumar/Desktop/Desktop/trainme.csv'  # Use the variable to read the file

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/premkumar/Desktop/Desktop/trainme.csv'

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mayankpatel14/second-hand-used-cars-data-set-linear-regression")

print("Path to dataset files:", path)

100%|██████████| 24.3k/24.3k [00:00<00:00, 14.5MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/mayankpatel14/second-hand-used-cars-data-set-linear-regression/versions/1


In [ ]:
import os
import pandas as pd

file_path = '/Users/premkumar/Desktop/Desktop/trainme.csv'

if os.path.exists(file_path):
    # If the file exists, read it into a DataFrame
    df = pd.read_csv(file_path)
    # Now you can use df, for example:
    print(df.head())
else:
    print(f"File not found at: {file_path}")

File not found at: /Users/premkumar/Desktop/Desktop/trainme.csv


In [ ]:
import os
import pandas as pd

file_path = '/Users/premkumar/Desktop/Desktop/secondhandcar.csv'

if os.path.exists(file_path):
    # If the file exists, read it into a DataFrame
    df = pd.read_csv(file_path)
    # Now you can use df, for example:
    print(df.head())
else:
    print(f"File not found at: {file_path}")

File not found at: /Users/premkumar/Desktop/Desktop/secondhandcar.csv


In [ ]:
data = pd.read_csv('/kaggle/input/second-hand-used-cars-data-set-linear-regression/train.csv')


FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/second-hand-used-cars-data-set-linear-regression/train.csv'

In [ ]:
import pandas as pd

   # Replace with the actual path where you extracted the dataset
   data_path = '/Users/premkumar/Downloads/second-hand-used-cars-data-set-linear-regression/keepitreal.csv'

   data = pd.read_csv(data_path)
   print(data.head())

IndentationError: unexpected indent (<ipython-input-16-d64bf8d1c5b8>, line 4)

In [ ]:
import pandas as pd

# Replace with the actual path where you extracted the dataset
data_path = '/Users/premkumar/Downloads/second-hand-used-cars-data-set-linear-regression/keepitreal.csv'

data = pd.read_csv(data_path)
print(data.head())

FileNotFoundError: [Errno 2] No such file or directory: '/Users/premkumar/Downloads/second-hand-used-cars-data-set-linear-regression/keepitreal.csv'

In [ ]:
# Replace 'your_file.xlsx' with the desired name for your XLSX file
df.to_excel('//Users/premkumar/Downloads/keepitreal.xlsxpath/to/your_file.xlsx', index=False)

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

In [ ]:
df.to_excel('/Users/premkumar/Downloads/keepitreal.xlsx', index=False)


NameError: name 'df' is not defined